require("dotenv").config();

const connectOracle = require("./src/config/oracle");

async function test() {
  let connection;

  try {
    connection = await connectOracle();

    const sql = `
            CREATE TABLE APP_USER.REC_DEPOSIT_CORE
            (
                CORE_DEPOSIT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                RUN_ID NUMBER
                    NOT NULL,

                BUSINESS_DATE DATE
                    NOT NULL,

                DEPOSIT_AMOUNT NUMBER(30, 6)
                    NOT NULL,

                SOURCE_SYSTEM VARCHAR2(50)
                    DEFAULT 'DB2'
                    NOT NULL,

                CURRENCY_CODE VARCHAR2(10)
                    DEFAULT 'ETB'
                    NOT NULL,

                STATUS VARCHAR2(20)
                    DEFAULT 'SUCCESS'
                    NOT NULL,

                QUERY_START_TIME TIMESTAMP,

                QUERY_END_TIME TIMESTAMP,

                QUERY_DURATION_SECONDS NUMBER(12, 2),

                CREATED_BY VARCHAR2(50),

                CREATED_DATE TIMESTAMP
                    DEFAULT CURRENT_TIMESTAMP
                    NOT NULL,

                ERROR_MESSAGE VARCHAR2(1000),

                CONSTRAINT FK_CORE_DEPOSIT_RUN
                    FOREIGN KEY (RUN_ID)
                    REFERENCES APP_USER.REC_RECONCILIATION_RUN(RUN_ID),

                CONSTRAINT CK_CORE_DEPOSIT_STATUS
                    CHECK (STATUS IN ('SUCCESS', 'FAILED'))
            )
        `;

    await connection.execute(sql);

    console.log("REC_DEPOSIT_CORE table created successfully.");
  } catch (error) {
    console.error("CREATE TABLE FAILED:");
    console.error(error);
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

test();
