--------------------------------------------------------
-- EDRMS TABLES
--------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RECONCILIATION_RESULT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SEGMENT_DEPOSIT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DEPOSIT_SUMMARY CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RECONCILIATION_RUN CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

--------------------------------------------------------

CREATE TABLE REC_RECONCILIATION_RUN
(
    RUN_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    BUSINESS_DATE DATE NOT NULL,

    START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    END_TIME TIMESTAMP,

    STATUS VARCHAR2(20),

    CREATED_BY VARCHAR2(50),

    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--------------------------------------------------------

-- CREATE TABLE DEPOSIT_SUMMARY
-- (
--     SUMMARY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

--     BUSINESS_DATE DATE,

--     SOURCE_SYSTEM VARCHAR2(30),

--     TOTAL_DEPOSIT NUMBER(18,2),

--     RETAIL_DEPOSIT NUMBER(18,2),

--     SEGMENTATION_DEPOSIT NUMBER(18,2),

--     CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

--------------------------------------------------------

-- CREATE TABLE SEGMENT_DEPOSIT
-- (
--     SEGMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

--     BUSINESS_DATE DATE,

--     SOURCE_SYSTEM VARCHAR2(30),

--     SEGMENT_NAME VARCHAR2(50),

--     AMOUNT NUMBER(18,2),

--     CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

--------------------------------------------------------

CREATE TABLE REC_RECONCILIATION_RESULT
(
    RESULT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    RUN_ID NUMBER,

    RULE_NAME VARCHAR2(100),

    STATUS VARCHAR2(20),

    EXPECTED_VALUE NUMBER(18,2),

    ACTUAL_VALUE NUMBER(18,2),

    DIFFERENCE NUMBER(18,2),

    MESSAGE VARCHAR2(500),

    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_RESULT_RUN
    FOREIGN KEY(RUN_ID)
    REFERENCES RECONCILIATION_RUN(RUN_ID)
);


CREATE TABLE REC_EDRMS_USERS
(
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    USERNAME VARCHAR2(50) UNIQUE NOT NULL,

    PASSWORD_HASH VARCHAR2(255) NOT NULL,

    FULL_NAME VARCHAR2(100),

    ROLE VARCHAR2(20) NOT NULL,

    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',

    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE REC_RECONCILIATION_SCHEDULE
(

    SCHEDULE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,


    SCHEDULE_NAME VARCHAR2(100)
    NOT NULL,


    RUN_TYPE VARCHAR2(30)
    NOT NULL,


    RUN_TIME VARCHAR2(5)
    NOT NULL,


    DAYS_OF_WEEK VARCHAR2(100),


    TIMEZONE VARCHAR2(50)
    DEFAULT 'Africa/Addis_Ababa',


    STATUS VARCHAR2(20)
    DEFAULT 'ACTIVE',


    CREATED_BY VARCHAR2(50),


    CREATED_DATE TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP,


    UPDATED_DATE TIMESTAMP

);


CREATE TABLE REC_RECONCILIATION_JOB_HISTORY
(

JOB_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
PRIMARY KEY,


RUN_ID NUMBER,


JOB_TYPE VARCHAR2(20),


START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


END_TIME TIMESTAMP,


STATUS VARCHAR2(20),


ERROR_MESSAGE VARCHAR2(500),


CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


CONSTRAINT FK_JOB_RUN

FOREIGN KEY(RUN_ID)

REFERENCES TESTUSER.RECONCILIATION_RUN(RUN_ID)

);


CREATE TABLE REC_NOTIFICATION_HISTORY
(

    NOTIFICATION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,


    RUN_ID NUMBER,


    NOTIFICATION_TYPE VARCHAR2(50)
    NOT NULL,


    RECIPIENT VARCHAR2(200),


    SUBJECT VARCHAR2(200),


    MESSAGE VARCHAR2(1000),


    STATUS VARCHAR2(20)
    DEFAULT 'SENT',


    CREATED_DATE TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP

);

-- CREATE TABLE TESTUSER.NOTIFICATION_CONFIG
-- (

--     CONFIG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
--     PRIMARY KEY,


--     EVENT_TYPE VARCHAR2(50)
--     NOT NULL,


--     ENABLED VARCHAR2(10)
--     DEFAULT 'YES',


--     EMAIL_TO VARCHAR2(500),


--     CREATED_DATE TIMESTAMP
--     DEFAULT CURRENT_TIMESTAMP

-- );

CREATE TABLE REC_NOTIFICATION_CONFIG
(

    CONFIG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,


    EVENT_TYPE VARCHAR2(50)
    NOT NULL,


    EMAIL_ENABLED VARCHAR2(10)
    DEFAULT 'YES',


    EMAIL_TO VARCHAR2(500)
    NOT NULL,


    SUBJECT VARCHAR2(200),


    CREATED_BY VARCHAR2(50),


    CREATED_DATE TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP,


    UPDATED_DATE TIMESTAMP

);


-- Update DDL for Deposit Summary
CREATE TABLE REC_DEPOSIT_SUMMARY_RECONCILATION
(
    SUMMARY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    BUSINESS_DATE DATE NOT NULL,

    SOURCE_SYSTEM VARCHAR2(30) DEFAULT 'DWH',

    -- Overall deposit
    TOTAL_DEPOSIT NUMBER(18,2),

    TOTAL_CONVENTIONAL NUMBER(18,2),

    TOTAL_IFB NUMBER(18,2),

    -- Retail deposits
    RETAIL_TOTAL_DEPOSIT NUMBER(18,2),

    CONVENTIONAL_RETAIL_TOTAL NUMBER(18,2),

    IFB_RETAIL_TOTAL NUMBER(18,2),

    -- Segment deposits
    SEGMENT_TOTAL_DEPOSIT NUMBER(18,2),

    CONVENTIONAL_SEGMENT_TOTAL NUMBER(18,2),

    IFB_SEGMENT_TOTAL NUMBER(18,2),

    -- Individual segment deposits
    CORPORATE NUMBER(18,2),

    IFBCRM NUMBER(18,2),

    SME NUMBER(18,2),

    BUSINESS NUMBER(18,2),

    GOVERNMENT NUMBER(18,2),

    MULTINATIONAL NUMBER(18,2),

    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- -------------------------------------------- PROCEDURE ------------------------------------------------------------

create or replace PROCEDURE LOAD_DWH_DEPOSIT_SUMMARY

(

    p_business_date IN DATE DEFAULT TRUNC(SYSDATE)

)

AS

BEGIN
 
    -- Prevent duplicate summary for the same business date

    DELETE FROM CBS.DEPOSIT_SUMMARY_RECONCILATION

    WHERE trunc(BUSINESS_DATE) = trunc(sysdate)

      AND SOURCE_SYSTEM = 'DWH';


    INSERT INTO REC_DEPOSIT_SUMMARY_RECONCILATION

    (

        BUSINESS_DATE,
        SOURCE_SYSTEM,
        TOTAL_DEPOSIT,
        TOTAL_CONVENTIONAL,
        TOTAL_IFB,
        RETAIL_TOTAL_DEPOSIT,
        CONVENTIONAL_RETAIL_TOTAL,
        IFB_RETAIL_TOTAL,
        SEGMENT_TOTAL_DEPOSIT,
        CONVENTIONAL_SEGMENT_TOTAL,
        IFB_SEGMENT_TOTAL,
        CORPORATE,
        IFBCRM,
        SME,
        BUSINESS,
        GOVERNMENT,
        MULTINATIONAL
    )
        
     select * from REC_VW_REC_DEPOSIT

    -- Prints Total Deposit calculating from MV_DAILY_SUMMARY_OF_DEPOSIT table
 
 
    COMMIT;
 
EXCEPTION

    WHEN OTHERS THEN

        ROLLBACK;

        RAISE;

END;
 

 ------------------------------------------------------ VIEW TO SELECT ALL / FETCH / DATA -------------------------------------------------------

 CREATE VIEW REC_VW_REC_DEPOSIT AS 
     -- Prints Total Deposit calculating from MV_DAILY_SUMMARY_OF_DEPOSIT table
WITH WarehouseTotalDeposit AS (
SELECT sum(Total_Deposit_first) AS Warehouse_Deposit_Summar 
FROM(
SELECT T.Total_Deposit_first,T.Total_margin_first, (Total_Deposit_first - Total_margin_first)  AS Branch_Total_Deposit
FROM 
(SELECT 
mdsod.*,
(mdsod.CURRENTACCOUNTBALANCE + mdsod.SAVINGS +mdsod.SPECIALSAV + mdsod.TIMEDEPOSIT + mdsod.OD + mdsod.IFBDEPOSIT ) AS Total_Deposit_first, 
(mdsod.MARGINHELDBALANCE + mdsod.MARGINIFBHELDBALANCE ) AS Total_margin_first 
FROM CBS.MV_DAILY_SUMMARY_OF_DEPOSIT mdsod  --Summary of Deposit 
) T
)
)
--SELECT sum(Total_Deposit_first) AS Warehouse_Deposit_Summar FROM BranchTotal
---------------------------------------------------------- End of Total Deposit From Daily Summary -----------------------------------------------------------------------

-- Prints Yesterday Total Deposit
--SELECT sum(YESTERDAYBALANCE) AS Warehouse_Total_deposit_yesterday FROM CBS.MV_DEPOSIT_AS_OF_YESTERDAY 
---------------------------------------------------------- End of Total Deposit From Deposit as of Yesterday -------------------------------------------------------------

---------------------------------------------------------- Start of Calculating Retail Total Deposit --------------------------------------------------------------------
--Prints Total Conventional Deposit
,ConventionalRetailDeposit as
(
SELECT sum(a.SHADOWCLEAREDBALANCE) as convTotalBalance ,count(distinct a.ACCOUNTID ) as countOftotal ,a.branchcode as totalBranch, b.branchType
FROM  cbs.MV_ACCOUNT_BALANCE_D a
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('Savings','SpecialSAV','notice','fixdep') OR 
(a.PRODUCT_ACC_PRODUCTID='CurrentAccount' and  a.accountid NOT in ('01304005574300','013041194227701')) OR 
((a.PRODUCT_ACC_PRODUCTID='OverDrafts' or  a.accountid = '01304005574300') and  a.SHADOWCLEAREDBALANCE > 0)) 
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) and a.UBSUBPRODUCTID not in ('01438','01432')
and a.segmentname ='Retail' and a.SHADOWCLEAREDBALANCE < 20000000
group by a.branchcode, b.branchType
)
,
ConventionalRetailDepositabove20mil as
(
SELECT sum(a.SHADOWCLEAREDBALANCE) as convTotalBalance ,count(distinct a.ACCOUNTID ) as countOftotal ,a.branchcode as totalBranch, b.branchType
FROM  cbs.MV_ACCOUNT_BALANCE_D a
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('Savings','SpecialSAV','notice','fixdep') OR 
(a.PRODUCT_ACC_PRODUCTID='CurrentAccount' and  a.accountid NOT in ('01304005574300','013041194227701')) OR 
((a.PRODUCT_ACC_PRODUCTID='OverDrafts' or  a.accountid = '01304005574300') and  a.SHADOWCLEAREDBALANCE > 0)) 
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) and a.UBSUBPRODUCTID not in ('01438','01432')
and a.segmentname ='Retail' AND a.SHADOWCLEAREDBALANCE >= 20000000
group by a.branchcode, b.branchType
),
TotalConvenDepositRetail AS
(
SELECT sum(t.CONV1 ) AS Conve_Total_Deposit_Retail
FROM (
SELECT sum(convTotalBalance) AS conv1 FROM ConventionalRetailDeposit
UNION
SELECT sum(convTotalBalance) AS conv2 FROM ConventionalRetailDepositabove20mil
) t
),
--SELECT * FROM TotalConvenDepositRetail
------------------------------------------------------------------- End of Conventional Total Deposit --------------------------------------------------------------------
--Prints Total IFB Deposit
IFBRetailDepositavove20mil as
(
SELECT sum(a.SHADOWCLEAREDBALANCE) as IFBtotalBalance ,count(distinct a.ACCOUNTID ) as countOftotal ,a.branchcode as totalBranch, b.branchType
FROM  cbs.MV_ACCOUNT_BALANCE_D a
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('IFBCurrent','IFBSavings','IFBSpecialSAV','MudarabaInvest') or a.UBSUBPRODUCTID in ('01438','01432') OR a.accountid='013041194227701') 
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) 
and a.segmentname ='Retail' AND a.SHADOWCLEAREDBALANCE >= 20000000
group by a.branchcode, b.branchType

)
,
IFBRetailDeposit as
(
SELECT sum(a.SHADOWCLEAREDBALANCE) as IFBtotalBalance ,count(distinct a.ACCOUNTID ) as countOftotal ,a.branchcode as totalBranch, b.branchType
FROM  cbs.MV_ACCOUNT_BALANCE_D a
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('IFBCurrent','IFBSavings','IFBSpecialSAV','MudarabaInvest') or a.UBSUBPRODUCTID in ('01438','01432') OR a.accountid='013041194227701') 
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) 
and a.segmentname ='Retail' and a.SHADOWCLEAREDBALANCE < 20000000
group by a.branchcode, b.branchType
),
TotalIFBDepositRetail AS(
SELECT sum(t.IFBDep) AS IFB_Total_Deposit_Retail
FROM (
SELECT sum(IFBTOTALBALANCE) AS IFBDep FROM IFBRetailDeposit
UNION
SELECT sum(IFBTOTALBALANCE) AS IFBDep FROM IFBRetailDepositavove20mil
) t
)
--SELECT * FROM TotalIFBDepositRetail
------------------------------------------------------------------------ End of IFB Total Deposit -------------------------------------------------------------------------------------
-- Print Retail Total Deposit
,RetailTotalDeposit AS (
SELECT sum(t.IFB_TOTAL_DEPOSIT_RETAIL) AS RetailTotalDeposit
FROM (
SELECT * FROM TotalIFBDepositRetail
UNION all
SELECT * FROM TotalConvenDepositRetail
)t
)
--------------------------------------------------------------End Of Retail Total Deposit------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------Start Of Segment Total Deposit---------------------------------------------------------------------------------------------------------
--Prints Total Conventional Segment Deposit
, SegmentDeposit as
(
select count(distinct a.accountid) as segmentCount,sum(a.SHADOWCLEAREDBALANCE) as SegmentBalance,a.branchcode as totalBranch,b.branchtype
from cbs.MV_ACCOUNT_BALANCE_D a
--inner join cbs.DIM_AIB_RMSEGMENT ra ON a.UBCUSTOMERCODE  = ra.CUSTOMERCODE
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('Savings','SpecialSAV','notice','fixdep') OR 
(a.PRODUCT_ACC_PRODUCTID='CurrentAccount' and  a.accountid NOT in ('01304005574300','013041194227701')) OR 
((a.PRODUCT_ACC_PRODUCTID='OverDrafts' or  a.accountid = '01304005574300') and  a.SHADOWCLEAREDBALANCE > 0)) and a.UBSUBPRODUCTID not in ('01438','01432')
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) and a.SHADOWCLEAREDBALANCE < 20000000
and a.segmentname <> 'Retail'
group by a.branchcode, b.branchType
),
SegmentDepositabove20mil as
(
select count(distinct a.accountid) as segmentCount,sum(a.SHADOWCLEAREDBALANCE) as SegmentBalance,a.branchcode as totalBranch,b.branchtype
from cbs.MV_ACCOUNT_BALANCE_D a
--inner join cbs.DIM_AIB_RMSEGMENT ra ON a.UBCUSTOMERCODE  = ra.CUSTOMERCODE
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('Savings','SpecialSAV','notice','fixdep') OR 
(a.PRODUCT_ACC_PRODUCTID='CurrentAccount' and  a.accountid NOT in ('01304005574300','013041194227701')) OR 
((a.PRODUCT_ACC_PRODUCTID='OverDrafts' or  a.accountid = '01304005574300') and  a.SHADOWCLEAREDBALANCE > 0)) and a.UBSUBPRODUCTID not in ('01438','01432')
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) AND a.SHADOWCLEAREDBALANCE >= 20000000
and a.segmentname <> 'Retail'
group by a.branchcode, b.branchType
),
TotalConvenDepositSegment AS
(
SELECT sum(t.convSegment1) AS Conve_Total_Deposit_Retail
FROM (
SELECT sum(SEGMENTBALANCE) AS convSegment1 FROM SegmentDeposit
union
SELECT sum(SEGMENTBALANCE) AS convSegment2 FROM SegmentDepositabove20mil
) t
),

-- SELECT * FROM TotalConvenDepositSegment
------------------------------------------------------------------- End of Conventional Total Deposit Segment--------------------------------------------------------------------
--Prints Total IFB Deposit Segment
IFBSegmentDepositavove20mil as
(
SELECT sum(a.SHADOWCLEAREDBALANCE) as IFBtotalBalance ,count( a.ACCOUNTID ) as countOftotal ,a.branchcode as totalBranch, b.branchType
FROM  cbs.MV_ACCOUNT_BALANCE_D a
--inner join cbs.DIM_AIB_RMSEGMENT ra ON a.UBCUSTOMERCODE  = ra.CUSTOMERCODE
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('IFBCurrent','IFBSavings','IFBSpecialSAV','MudarabaInvest') or a.UBSUBPRODUCTID in ('01438','01432') OR a.accountid='013041194227701') 
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0))
and  a.SHADOWCLEAREDBALANCE >= 20000000 and a.segmentname <> 'Retail'
group by a.branchcode, b.branchType
)
,
IFBSegmentDeposit as
(
SELECT sum(a.SHADOWCLEAREDBALANCE) as IFBtotalBalance ,count( a.ACCOUNTID ) as countOftotal ,a.branchcode as totalBranch, b.branchType
FROM  cbs.MV_ACCOUNT_BALANCE_D a
--inner join cbs.DIM_AIB_RMSEGMENT ra ON a.UBCUSTOMERCODE  = ra.CUSTOMERCODE
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('IFBCurrent','IFBSavings','IFBSpecialSAV','MudarabaInvest') or a.UBSUBPRODUCTID in ('01438','01432') OR a.accountid='013041194227701' ) 
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) and a.SHADOWCLEAREDBALANCE < 20000000
and a.segmentname <> 'Retail'
group by a.branchcode, b.branchType
),

TotalIFBDepositSegment AS(
SELECT sum(t.IFBDepSegment1) AS IFB_Total_Deposit_Segment
FROM (
SELECT sum(IFBTOTALBALANCE) AS IFBDepSegment1 FROM IFBSegmentDeposit
union
SELECT sum(IFBTOTALBALANCE) AS IFBDepSegment2 FROM IFBSegmentDepositavove20mil
) t
),
--- SELECT * FROM TotalIFBDepositSegment
------------------------------------------------------------------------ End of IFB Total Deposit Segment -------------------------------------------------------------------------------------
-- Print Retail Total Deposit
SegmentTotalDeposit AS (
SELECT sum(t.IFB_Total_Deposit_Segment) AS RetailTotalDeposit
FROM (
SELECT * FROM TotalIFBDepositSegment
UNION ALL 
SELECT * FROM TotalConvenDepositSegment
)t
),
--------------------------------------------------------------End Of Segment Total Deposit------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------- Start of Indicvidual Segment ----------------------------------------------------------------------------------------------------------
individualSegment AS
(
    SELECT
        SUM(CASE WHEN SEGMENTNAME='CORPORATE'
                 THEN Individual_Total_deposit ELSE 0 END) AS CORPORATE,

        SUM(CASE WHEN SEGMENTNAME='IFBCRM'
                 THEN Individual_Total_deposit ELSE 0 END) AS IFBCRM,

        SUM(CASE WHEN SEGMENTNAME='SME'
                 THEN Individual_Total_deposit ELSE 0 END) AS SME,

        SUM(CASE WHEN SEGMENTNAME='BUSINESS'
                 THEN Individual_Total_deposit ELSE 0 END) AS BUSINESS,

        SUM(CASE WHEN SEGMENTNAME='GOVERNMENT'
                 THEN Individual_Total_deposit ELSE 0 END) AS GOVERNMENT,

        SUM(CASE WHEN SEGMENTNAME='MULTINATIONAL'
                 THEN Individual_Total_deposit ELSE 0 END) AS MULTINATIONAL

    FROM
    (
        SELECT
            CASE
                WHEN SEGMENTNAME IN ('INSTITUTIONAL','GOVERNMENT')
                THEN 'GOVERNMENT'
                ELSE SEGMENTNAME
            END AS SEGMENTNAME,
            SUM(YESTERDAYBALANCE) AS Individual_Total_deposit
        FROM CBS.MV_DEPOSIT_AS_OF_YESTERDAY
        GROUP BY
            CASE
                WHEN SEGMENTNAME IN ('INSTITUTIONAL','GOVERNMENT')
                THEN 'GOVERNMENT'
                ELSE SEGMENTNAME
            END
    )
),
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    FinalSummary AS
    (
        SELECT
            Warehouse_Deposit_Summar AS TOTAL_DEPOSIT,

            (
                SELECT Conve_Total_Deposit_Retail
                FROM TotalConvenDepositRetail
            )
            +
            (
                SELECT Conve_Total_Deposit_Retail
                FROM TotalConvenDepositSegment
            ) AS TOTAL_CONVENTIONAL,

            (
                SELECT IFB_Total_Deposit_Retail
                FROM TotalIFBDepositRetail
            )
            +
            (
                SELECT IFB_Total_Deposit_Segment
                FROM TotalIFBDepositSegment
            ) AS TOTAL_IFB,

            (
                SELECT RetailTotalDeposit
                FROM RetailTotalDeposit
            ) AS RETAIL_TOTAL_DEPOSIT,

            (
                SELECT Conve_Total_Deposit_Retail
                FROM TotalConvenDepositRetail
            ) AS CONVENTIONAL_RETAIL_TOTAL,

            (
                SELECT IFB_Total_Deposit_Retail
                FROM TotalIFBDepositRetail
            ) AS IFB_RETAIL_TOTAL,

            (
                SELECT RetailTotalDeposit
                FROM SegmentTotalDeposit
            ) AS SEGMENT_TOTAL_DEPOSIT,

            (
                SELECT Conve_Total_Deposit_Retail
                FROM TotalConvenDepositSegment
            ) AS CONVENTIONAL_SEGMENT_TOTAL,

            (
                SELECT IFB_Total_Deposit_Segment
                FROM TotalIFBDepositSegment
            ) AS IFB_SEGMENT_TOTAL,
			(
			    SELECT CORPORATE
			    FROM individualSegment
			) AS CORPORATE,

			(
			    SELECT IFBCRM
			    FROM individualSegment
			) AS IFBCRM,
			
			(
			    SELECT SME
			    FROM individualSegment
			) AS SME,
			
			(
			    SELECT BUSINESS
			    FROM individualSegment
			) AS BUSINESS,
			
			(
			    SELECT GOVERNMENT
			    FROM individualSegment
			) AS GOVERNMENT,
			
			(
			    SELECT MULTINATIONAL
			    FROM individualSegment
			) AS MULTINATIONAL
        FROM WarehouseTotalDeposit
    )

    SELECT
        -- p_business_date,
        sysdate,
        'DWH'AS DWH,
        ROUND(TOTAL_DEPOSIT,2) AS TOTAL_DEPOSIT,
        ROUND(TOTAL_CONVENTIONAL,2) AS TOTAL_CONVENTIONAL,
        ROUND(TOTAL_IFB,2) AS TOTAL_IFB,
        ROUND(RETAIL_TOTAL_DEPOSIT,2) AS RETAIL_TOTAL_DEPOSIT,
        ROUND(CONVENTIONAL_RETAIL_TOTAL,2) AS CONVENTIONAL_RETAIL_TOTAL,
        ROUND(IFB_RETAIL_TOTAL,2) AS IFB_RETAIL_TOTAL,
        ROUND(SEGMENT_TOTAL_DEPOSIT,2) AS SEGMENT_TOTAL_DEPOSIT,
        ROUND(CONVENTIONAL_SEGMENT_TOTAL,2) AS CONVENTIONAL_SEGMENT_TOTAL,
        ROUND(IFB_SEGMENT_TOTAL,2) AS IFB_SEGMENT_TOTAL,
        ROUND(CORPORATE,2) AS CORPORATE,
        ROUND(IFBCRM,2) AS IFBCRM,
	    ROUND(SME,2) AS SME,
	    ROUND(BUSINESS,2) AS BUSINESS,
	    ROUND(GOVERNMENT,2) AS GOVERNMENT,
	    ROUND(MULTINATIONAL,2) AS MULTINATIONAL

	FROM FinalSummary;






    -------------------------------------------------- OPTIMIZED FINAL VIEW CENTS LEVEL ---------------------------------------------
    CREATE VIEW REC_VW_REC_DEPOSIT AS 
     -- Prints Total Deposit calculating from MV_DAILY_SUMMARY_OF_DEPOSIT table
WITH WarehouseTotalDeposit AS (
SELECT sum(YESTERDAYBALANCE) AS Warehouse_Deposit_Summar FROM CBS.MV_DEPOSIT_AS_OF_YESTERDAY

---------------------------------------------------------- End of Total Deposit From Daily Summary -----------------------------------------------------------------------

-- Prints Yesterday Total Deposit
--SELECT sum(YESTERDAYBALANCE) AS Warehouse_Total_deposit_yesterday FROM CBS.MV_DEPOSIT_AS_OF_YESTERDAY 
---------------------------------------------------------- End of Total Deposit From Deposit as of Yesterday -------------------------------------------------------------

---------------------------------------------------------- Start of Calculating Retail Total Deposit --------------------------------------------------------------------
--Prints Total Conventional Deposit
,ConventionalRetailDeposit as
(
SELECT sum(a.SHADOWCLEAREDBALANCE) as convTotalBalance ,count(distinct a.ACCOUNTID ) as countOftotal ,a.branchcode as totalBranch, b.branchType
FROM  cbs.MV_ACCOUNT_BALANCE_D a
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('Savings','SpecialSAV','notice','fixdep') OR 
(a.PRODUCT_ACC_PRODUCTID='CurrentAccount' and  a.accountid NOT in ('01304005574300','013041194227701')) OR 
((a.PRODUCT_ACC_PRODUCTID='OverDrafts' or  a.accountid = '01304005574300') and  a.SHADOWCLEAREDBALANCE > 0)) 
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) and a.UBSUBPRODUCTID not in ('01438','01432')
and a.segmentname ='Retail' and a.SHADOWCLEAREDBALANCE < 20000000
group by a.branchcode, b.branchType
)
,
ConventionalRetailDepositabove20mil as
(
SELECT sum(a.SHADOWCLEAREDBALANCE) as convTotalBalance ,count(distinct a.ACCOUNTID ) as countOftotal ,a.branchcode as totalBranch, b.branchType
FROM  cbs.MV_ACCOUNT_BALANCE_D a
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('Savings','SpecialSAV','notice','fixdep') OR 
(a.PRODUCT_ACC_PRODUCTID='CurrentAccount' and  a.accountid NOT in ('01304005574300','013041194227701')) OR 
((a.PRODUCT_ACC_PRODUCTID='OverDrafts' or  a.accountid = '01304005574300') and  a.SHADOWCLEAREDBALANCE > 0)) 
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) and a.UBSUBPRODUCTID not in ('01438','01432')
and a.segmentname ='Retail' AND a.SHADOWCLEAREDBALANCE >= 20000000
group by a.branchcode, b.branchType
),
TotalConvenDepositRetail AS
(
SELECT sum(t.CONV1 ) AS Conve_Total_Deposit_Retail
FROM (
SELECT sum(convTotalBalance) AS conv1 FROM ConventionalRetailDeposit
UNION
SELECT sum(convTotalBalance) AS conv2 FROM ConventionalRetailDepositabove20mil
) t
),
--SELECT * FROM TotalConvenDepositRetail
------------------------------------------------------------------- End of Conventional Total Deposit --------------------------------------------------------------------
--Prints Total IFB Deposit
IFBRetailDepositavove20mil as
(
SELECT sum(a.SHADOWCLEAREDBALANCE) as IFBtotalBalance ,count(distinct a.ACCOUNTID ) as countOftotal ,a.branchcode as totalBranch, b.branchType
FROM  cbs.MV_ACCOUNT_BALANCE_D a
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('IFBCurrent','IFBSavings','IFBSpecialSAV','MudarabaInvest') or a.UBSUBPRODUCTID in ('01438','01432') OR a.accountid='013041194227701') 
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) 
and a.segmentname ='Retail' AND a.SHADOWCLEAREDBALANCE >= 20000000
group by a.branchcode, b.branchType

)
,
IFBRetailDeposit as
(
SELECT sum(a.SHADOWCLEAREDBALANCE) as IFBtotalBalance ,count(distinct a.ACCOUNTID ) as countOftotal ,a.branchcode as totalBranch, b.branchType
FROM  cbs.MV_ACCOUNT_BALANCE_D a
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('IFBCurrent','IFBSavings','IFBSpecialSAV','MudarabaInvest') or a.UBSUBPRODUCTID in ('01438','01432') OR a.accountid='013041194227701') 
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) 
and a.segmentname ='Retail' and a.SHADOWCLEAREDBALANCE < 20000000
group by a.branchcode, b.branchType
),
TotalIFBDepositRetail AS(
SELECT sum(t.IFBDep) AS IFB_Total_Deposit_Retail
FROM (
SELECT sum(IFBTOTALBALANCE) AS IFBDep FROM IFBRetailDeposit
UNION
SELECT sum(IFBTOTALBALANCE) AS IFBDep FROM IFBRetailDepositavove20mil
) t
)
--SELECT * FROM TotalIFBDepositRetail
------------------------------------------------------------------------ End of IFB Total Deposit -------------------------------------------------------------------------------------
-- Print Retail Total Deposit
,RetailTotalDeposit AS (
SELECT sum(t.IFB_TOTAL_DEPOSIT_RETAIL) AS RetailTotalDeposit
FROM (
SELECT * FROM TotalIFBDepositRetail
UNION all
SELECT * FROM TotalConvenDepositRetail
)t
)
--------------------------------------------------------------End Of Retail Total Deposit------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------Start Of Segment Total Deposit---------------------------------------------------------------------------------------------------------
--Prints Total Conventional Segment Deposit
, SegmentDeposit as
(
select count(distinct a.accountid) as segmentCount,sum(a.SHADOWCLEAREDBALANCE) as SegmentBalance,a.branchcode as totalBranch,b.branchtype
from cbs.MV_ACCOUNT_BALANCE_D a
--inner join cbs.DIM_AIB_RMSEGMENT ra ON a.UBCUSTOMERCODE  = ra.CUSTOMERCODE
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('Savings','SpecialSAV','notice','fixdep') OR 
(a.PRODUCT_ACC_PRODUCTID='CurrentAccount' and  a.accountid NOT in ('01304005574300','013041194227701')) OR 
((a.PRODUCT_ACC_PRODUCTID='OverDrafts' or  a.accountid = '01304005574300') and  a.SHADOWCLEAREDBALANCE > 0)) and a.UBSUBPRODUCTID not in ('01438','01432')
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) and a.SHADOWCLEAREDBALANCE < 20000000
and a.segmentname <> 'Retail'
group by a.branchcode, b.branchType
),
SegmentDepositabove20mil as
(
select count(distinct a.accountid) as segmentCount,sum(a.SHADOWCLEAREDBALANCE) as SegmentBalance,a.branchcode as totalBranch,b.branchtype
from cbs.MV_ACCOUNT_BALANCE_D a
--inner join cbs.DIM_AIB_RMSEGMENT ra ON a.UBCUSTOMERCODE  = ra.CUSTOMERCODE
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('Savings','SpecialSAV','notice','fixdep') OR 
(a.PRODUCT_ACC_PRODUCTID='CurrentAccount' and  a.accountid NOT in ('01304005574300','013041194227701')) OR 
((a.PRODUCT_ACC_PRODUCTID='OverDrafts' or  a.accountid = '01304005574300') and  a.SHADOWCLEAREDBALANCE > 0)) and a.UBSUBPRODUCTID not in ('01438','01432')
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) AND a.SHADOWCLEAREDBALANCE >= 20000000
and a.segmentname <> 'Retail'
group by a.branchcode, b.branchType
),
TotalConvenDepositSegment AS
(
SELECT sum(t.convSegment1) AS Conve_Total_Deposit_Retail
FROM (
SELECT sum(SEGMENTBALANCE) AS convSegment1 FROM SegmentDeposit
union
SELECT sum(SEGMENTBALANCE) AS convSegment2 FROM SegmentDepositabove20mil
) t
),

-- SELECT * FROM TotalConvenDepositSegment
------------------------------------------------------------------- End of Conventional Total Deposit Segment--------------------------------------------------------------------
--Prints Total IFB Deposit Segment
IFBSegmentDepositavove20mil as
(
SELECT sum(a.SHADOWCLEAREDBALANCE) as IFBtotalBalance ,count( a.ACCOUNTID ) as countOftotal ,a.branchcode as totalBranch, b.branchType
FROM  cbs.MV_ACCOUNT_BALANCE_D a
--inner join cbs.DIM_AIB_RMSEGMENT ra ON a.UBCUSTOMERCODE  = ra.CUSTOMERCODE
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('IFBCurrent','IFBSavings','IFBSpecialSAV','MudarabaInvest') or a.UBSUBPRODUCTID in ('01438','01432') OR a.accountid='013041194227701') 
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0))
and  a.SHADOWCLEAREDBALANCE >= 20000000 and a.segmentname <> 'Retail'
group by a.branchcode, b.branchType
)
,
IFBSegmentDeposit as
(
SELECT sum(a.SHADOWCLEAREDBALANCE) as IFBtotalBalance ,count( a.ACCOUNTID ) as countOftotal ,a.branchcode as totalBranch, b.branchType
FROM  cbs.MV_ACCOUNT_BALANCE_D a
--inner join cbs.DIM_AIB_RMSEGMENT ra ON a.UBCUSTOMERCODE  = ra.CUSTOMERCODE
inner join cbs.MV_BRANCHS_FOR_DEPOSIT b on b.branchcode = a.branchcode and b.branchtype = a.branchtype
where (a.PRODUCT_ACC_PRODUCTID in ('IFBCurrent','IFBSavings','IFBSpecialSAV','MudarabaInvest') or a.UBSUBPRODUCTID in ('01438','01432') OR a.accountid='013041194227701' ) 
and (a.closed='N' or (a.closed='Y' and a.SHADOWCLEAREDBALANCE <> 0)) and a.SHADOWCLEAREDBALANCE < 20000000
and a.segmentname <> 'Retail'
group by a.branchcode, b.branchType
),

TotalIFBDepositSegment AS(
SELECT sum(t.IFBDepSegment1) AS IFB_Total_Deposit_Segment
FROM (
SELECT sum(IFBTOTALBALANCE) AS IFBDepSegment1 FROM IFBSegmentDeposit
union
SELECT sum(IFBTOTALBALANCE) AS IFBDepSegment2 FROM IFBSegmentDepositavove20mil
) t
),
--- SELECT * FROM TotalIFBDepositSegment
------------------------------------------------------------------------ End of IFB Total Deposit Segment -------------------------------------------------------------------------------------
-- Print Retail Total Deposit
SegmentTotalDeposit AS (
SELECT sum(t.IFB_Total_Deposit_Segment) AS RetailTotalDeposit
FROM (
SELECT * FROM TotalIFBDepositSegment
UNION ALL 
SELECT * FROM TotalConvenDepositSegment
)t
),
--------------------------------------------------------------End Of Segment Total Deposit------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------- Start of Indicvidual Segment ----------------------------------------------------------------------------------------------------------
individualSegment AS
(
    SELECT
        SUM(CASE WHEN SEGMENTNAME='CORPORATE'
                 THEN Individual_Total_deposit ELSE 0 END) AS CORPORATE,

        SUM(CASE WHEN SEGMENTNAME='IFBCRM'
                 THEN Individual_Total_deposit ELSE 0 END) AS IFBCRM,

        SUM(CASE WHEN SEGMENTNAME='SME'
                 THEN Individual_Total_deposit ELSE 0 END) AS SME,

        SUM(CASE WHEN SEGMENTNAME='BUSINESS'
                 THEN Individual_Total_deposit ELSE 0 END) AS BUSINESS,

        SUM(CASE WHEN SEGMENTNAME='GOVERNMENT'
                 THEN Individual_Total_deposit ELSE 0 END) AS GOVERNMENT,

        SUM(CASE WHEN SEGMENTNAME='MULTINATIONAL'
                 THEN Individual_Total_deposit ELSE 0 END) AS MULTINATIONAL

    FROM
    (
        SELECT
            CASE
                WHEN SEGMENTNAME IN ('INSTITUTIONAL','GOVERNMENT')
                THEN 'GOVERNMENT'
                ELSE SEGMENTNAME
            END AS SEGMENTNAME,
            SUM(YESTERDAYBALANCE) AS Individual_Total_deposit
        FROM CBS.MV_DEPOSIT_AS_OF_YESTERDAY
        GROUP BY
            CASE
                WHEN SEGMENTNAME IN ('INSTITUTIONAL','GOVERNMENT')
                THEN 'GOVERNMENT'
                ELSE SEGMENTNAME
            END
    )
),
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    FinalSummary AS
    (
        SELECT
            Warehouse_Deposit_Summar AS TOTAL_DEPOSIT,

            (
                SELECT Conve_Total_Deposit_Retail
                FROM TotalConvenDepositRetail
            )
            +
            (
                SELECT Conve_Total_Deposit_Retail
                FROM TotalConvenDepositSegment
            ) AS TOTAL_CONVENTIONAL,

            (
                SELECT IFB_Total_Deposit_Retail
                FROM TotalIFBDepositRetail
            )
            +
            (
                SELECT IFB_Total_Deposit_Segment
                FROM TotalIFBDepositSegment
            ) AS TOTAL_IFB,

            (
                SELECT RetailTotalDeposit
                FROM RetailTotalDeposit
            ) AS RETAIL_TOTAL_DEPOSIT,

            (
                SELECT Conve_Total_Deposit_Retail
                FROM TotalConvenDepositRetail
            ) AS CONVENTIONAL_RETAIL_TOTAL,

            (
                SELECT IFB_Total_Deposit_Retail
                FROM TotalIFBDepositRetail
            ) AS IFB_RETAIL_TOTAL,

            (
                SELECT RetailTotalDeposit
                FROM SegmentTotalDeposit
            ) AS SEGMENT_TOTAL_DEPOSIT,

            (
                SELECT Conve_Total_Deposit_Retail
                FROM TotalConvenDepositSegment
            ) AS CONVENTIONAL_SEGMENT_TOTAL,

            (
                SELECT IFB_Total_Deposit_Segment
                FROM TotalIFBDepositSegment
            ) AS IFB_SEGMENT_TOTAL,
			(
			    SELECT CORPORATE
			    FROM individualSegment
			) AS CORPORATE,

			(
			    SELECT IFBCRM
			    FROM individualSegment
			) AS IFBCRM,
			
			(
			    SELECT SME
			    FROM individualSegment
			) AS SME,
			
			(
			    SELECT BUSINESS
			    FROM individualSegment
			) AS BUSINESS,
			
			(
			    SELECT GOVERNMENT
			    FROM individualSegment
			) AS GOVERNMENT,
			
			(
			    SELECT MULTINATIONAL
			    FROM individualSegment
			) AS MULTINATIONAL
        FROM WarehouseTotalDeposit
    )

    SELECT
        -- p_business_date,
        sysdate AS BUSINESS_DATE,
        'DWH'AS SOURCE_SYSTEM,
        TOTAL_DEPOSIT AS TOTAL_DEPOSIT,
        TOTAL_CONVENTIONAL AS TOTAL_CONVENTIONAL,
        TOTAL_IFB AS TOTAL_IFB,
        RETAIL_TOTAL_DEPOSIT AS RETAIL_TOTAL_DEPOSIT,
        CONVENTIONAL_RETAIL_TOTAL AS CONVENTIONAL_RETAIL_TOTAL,
        IFB_RETAIL_TOTAL AS IFB_RETAIL_TOTAL,
        SEGMENT_TOTAL_DEPOSIT AS SEGMENT_TOTAL_DEPOSIT,
        CONVENTIONAL_SEGMENT_TOTAL AS CONVENTIONAL_SEGMENT_TOTAL,
        IFB_SEGMENT_TOTAL AS IFB_SEGMENT_TOTAL,
        CORPORATE AS CORPORATE,
        IFBCRM AS IFBCRM,
	    SME AS SME,
	    BUSINESS AS BUSINESS,
	    GOVERNMENT AS GOVERNMENT,
	    MULTINATIONAL AS MULTINATIONAL

	FROM FinalSummary; 