DELETE FROM SEGMENT_DEPOSIT;

DELETE FROM DEPOSIT_SUMMARY;

COMMIT;

-------------------------------------------------------
-- CORE BANKING
-------------------------------------------------------

INSERT INTO DEPOSIT_SUMMARY
(
BUSINESS_DATE,
SOURCE_SYSTEM,
TOTAL_DEPOSIT,
RETAIL_DEPOSIT,
SEGMENTATION_DEPOSIT
)
VALUES
(
TRUNC(SYSDATE),
'CORE',
150000000,
90000000,
60000000
);

-------------------------------------------------------
-- DATA WAREHOUSE
-------------------------------------------------------

INSERT INTO DEPOSIT_SUMMARY
(
BUSINESS_DATE,
SOURCE_SYSTEM,
TOTAL_DEPOSIT,
RETAIL_DEPOSIT,
SEGMENTATION_DEPOSIT
)
VALUES
(
TRUNC(SYSDATE),
'DWH',
150000000,
90000000,
60000000
);

-------------------------------------------------------
-- SEGMENTS
-------------------------------------------------------

INSERT INTO SEGMENT_DEPOSIT
(BUSINESS_DATE,SOURCE_SYSTEM,SEGMENT_NAME,AMOUNT)
VALUES(TRUNC(SYSDATE),'DWH','SEGMENT1',10000000);

INSERT INTO SEGMENT_DEPOSIT
(BUSINESS_DATE,SOURCE_SYSTEM,SEGMENT_NAME,AMOUNT)
VALUES(TRUNC(SYSDATE),'DWH','SEGMENT2',12000000);

INSERT INTO SEGMENT_DEPOSIT
(BUSINESS_DATE,SOURCE_SYSTEM,SEGMENT_NAME,AMOUNT)
VALUES(TRUNC(SYSDATE),'DWH','SEGMENT3',8000000);

INSERT INTO SEGMENT_DEPOSIT
(BUSINESS_DATE,SOURCE_SYSTEM,SEGMENT_NAME,AMOUNT)
VALUES(TRUNC(SYSDATE),'DWH','SEGMENT4',7000000);

INSERT INTO SEGMENT_DEPOSIT
(BUSINESS_DATE,SOURCE_SYSTEM,SEGMENT_NAME,AMOUNT)
VALUES(TRUNC(SYSDATE),'DWH','SEGMENT5',5000000);

INSERT INTO SEGMENT_DEPOSIT
(BUSINESS_DATE,SOURCE_SYSTEM,SEGMENT_NAME,AMOUNT)
VALUES(TRUNC(SYSDATE),'DWH','SEGMENT6',18000000);

COMMIT;


INSERT INTO TESTUSER.NOTIFICATION_CONFIG
(
EVENT_TYPE,
ENABLED,
EMAIL_TO
)
VALUES
(
'RECONCILIATION_FAILURE',
'YES',
'admin@bank.com'
);



INSERT INTO TESTUSER.NOTIFICATION_CONFIG
(
EVENT_TYPE,
ENABLED,
EMAIL_TO
)
VALUES
(
'RECONCILIATION_SUCCESS',
'YES',
'admin@bank.com'
);


COMMIT;